"""Pydantic schemas for episode manifests and related domain objects."""

from karma.schemas.assets import AssetReference, AssetType
from karma.schemas.audio import AudioMaster, SceneAudio
from karma.schemas.episode import (
    EpisodeManifest,
    EpisodeStatus,
    OrchestrationState,
    QAStatus,
    ResearchState,
    ScriptState,
    StageCheckpoint,
    StageRunStatus,
    StoryState,
    VersionHistoryEntry,
)
from karma.schemas.publishing import (
    Approval,
    MetadataState,
    Privacy,
    PublishState,
    RenderState,
    ThumbnailState,
)
from karma.schemas.qa import (
    QACategory,
    QAIssue,
    QASeverity,
    QAVerdict,
    ScriptQAResult,
)
from karma.schemas.research import (
    ConfidenceLevel,
    ResearchBrief,
    ResearchClaim,
    ResearchSource,
)
from karma.schemas.production import (
    AssetGenerationKind,
    AssetProvenance,
    AssetRequirement,
    AssetSourceKind,
    AssetStatus,
    AssetType,
    AudioSpecification,
    CameraAngle,
    CameraMovement,
    CharacterAppearanceRequirement,
    ContinuityReference,
    DialogueTrackSpec,
    FramingType,
    LightingStyle,
    MasteringSpec,
    MoodType,
    MusicSpec,
    NarrationSpec,
    PlanningStatus,
    ProductionPlan,
    ProductionScene,
    ScenePlanningStatus,
    SFXSpec,
    VisualSpecification,
)
from karma.schemas.scene import Scene, SceneStatus
from karma.schemas.script import (
    EpisodeScript,
    ScriptLine,
    ScriptLineKind,
    ScriptScene,
)
from karma.schemas.story import (
    BeatType,
    CharacterRole,
    StoryArchitecture,
    StoryBeat,
    StoryCharacter,
)

__all__ = [
    "Approval",
    "AssetGenerationKind",
    "AssetProvenance",
    "AssetReference",
    "AssetRequirement",
    "AssetSourceKind",
    "AssetStatus",
    "AssetType",
    "AudioMaster",
    "AudioSpecification",
    "BeatType",
    "CameraAngle",
    "CameraMovement",
    "CharacterAppearanceRequirement",
    "CharacterRole",
    "ConfidenceLevel",
    "ContinuityReference",
    "DialogueTrackSpec",
    "FramingType",
    "EpisodeManifest",
    "EpisodeScript",
    "EpisodeStatus",
    "LightingStyle",
    "MasteringSpec",
    "MetadataState",
    "MoodType",
    "MusicSpec",
    "NarrationSpec",
    "OrchestrationState",
    "PlanningStatus",
    "Privacy",
    "ProductionPlan",
    "ProductionScene",
    "PublishState",
    "QAStatus",
    "QACategory",
    "QAIssue",
    "QASeverity",
    "QAVerdict",
    "RenderState",
    "ResearchBrief",
    "ResearchClaim",
    "ResearchSource",
    "Scene",
    "SceneAudio",
    "ScenePlanningStatus",
    "SceneStatus",
    "ScriptLine",
    "ScriptLineKind",
    "ScriptQAResult",
    "ScriptScene",
    "ScriptState",
    "StageCheckpoint",
    "StageRunStatus",
    "StoryArchitecture",
    "StoryBeat",
    "StoryCharacter",
    "StoryState",
    "SFXSpec",
    "ThumbnailState",
    "VersionHistoryEntry",
    "VisualSpecification",
]
